// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeXLqe_PvBEOmPct1DKoKxBmlDwvJ85aI',
    appId: '1:350007071181:web:4bfbda00a54b85e631f484',
    messagingSenderId: '350007071181',
    projectId: 'encareer-dtit',
    authDomain: 'encareer-dtit.firebaseapp.com',
    storageBucket: 'encareer-dtit.firebasestorage.app',
    measurementId: 'G-GCJ8092B5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7blv0fTokJ8D2ortuxeASWZl7VQoF0sA',
    appId: '1:350007071181:android:26cdba3de7001ef631f484',
    messagingSenderId: '350007071181',
    projectId: 'encareer-dtit',
    storageBucket: 'encareer-dtit.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeXLqe_PvBEOmPct1DKoKxBmlDwvJ85aI',
    appId: '1:350007071181:web:f4869eec464e842831f484',
    messagingSenderId: '350007071181',
    projectId: 'encareer-dtit',
    authDomain: 'encareer-dtit.firebaseapp.com',
    storageBucket: 'encareer-dtit.firebasestorage.app',
    measurementId: 'G-PRY4L7TP4X',
  );
}
